server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: scaa
          uri: http://localhost:8000
          predicates:
            - Path=/servcad/**
        - id: ass-cache
          uri: http://localhost:8080
          predicates:
            - Path=/ass-cache/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true